class PushException(BaseException):
    def __init__(self):
        pass
